services:
    rxu.advancedwarnings.listener:
        class: rxu\advancedwarnings\event\listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    rxu.advancedwarnings.cron.task.rxu_tidy_warnings:
        class: rxu\advancedwarnings\cron\task\rxu_tidy_warnings
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@cache.driver'
            - '@log'
        calls:
            - [set_name, [cron.task.core.rxu_tidy_warnings]]
        tags:
            - { name: cron.task }
