services:
    rxu.advanced_warnings.listener:
        class: rxu\advanced_warnings\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    rxu.advanced_warnings.cron.task.rxu_tidy_warnings:
        class: rxu\advanced_warnings\cron\task\rxu_tidy_warnings
        arguments:
            - @config
            - @dbal.conn
            - @user
            - @cache.driver
            - %core.root_path%
            - %core.php_ext%

        tags:
            - { name: cron.task }
